# Generated by Django 5.2.6 on 2025-10-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (max 500KB, auto-compressed if larger)",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
