# Generated by Django 5.2.6 on 2025-10-04 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_cases_case_updated_c10726_idx_and_more"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["case", "-created_at"], name="reports_rep_case_id_438755_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="reports_rep_created_9a90fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type"], name="reports_rep_report__dbb097_idx"
            ),
        ),
    ]
