# Generated by Django 5.2.6 on 2025-10-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("call", "Call Log"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("log", "System Log"),
                            ("contact", "Contact"),
                            ("location", "Location Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("device", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("content", models.TextField()),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("confidence", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("Person", "Person"),
                            ("Phone", "Phone Number"),
                            ("Email", "Email Address"),
                            ("Crypto", "Cryptocurrency Address"),
                            ("Location", "Location"),
                            ("GPS", "GPS Coordinates"),
                            ("URL", "URL"),
                            ("IP Address", "IP Address"),
                            ("Bank Account", "Bank Account"),
                            ("Document", "Document Reference"),
                            ("Codeword", "Codeword"),
                            ("Organization", "Organization"),
                            ("Date", "Date"),
                            ("Amount", "Amount"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("confidence", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="evidence.evidence",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_type", models.CharField(max_length=100)),
                ("strength", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="evidence.entity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="evidence.entity",
                    ),
                ),
                (
                    "evidence_items",
                    models.ManyToManyField(
                        related_name="connections", to="evidence.evidence"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["case", "type"], name="evidence_ev_case_id_0441d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["timestamp"], name="evidence_ev_timesta_718571_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(fields=["device"], name="evidence_ev_device_5f6ecb_idx"),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["entity_type", "value"], name="evidence_en_entity__f084b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("source_entity", "target_entity", "connection_type")},
        ),
    ]
