# Generated by Django 5.2.6 on 2025-10-04 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["-updated_at"], name="cases_case_updated_c10726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["status"], name="cases_case_status_5f99d2_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["case_number"], name="cases_case_case_nu_a07304_idx"
            ),
        ),
    ]
