# Generated by Django 5.2.6 on 2025-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("VIEW_EVIDENCE", "View Evidence"),
                            ("EXPORT_REPORT", "Export Report"),
                            ("RUN_SEARCH", "Run Search"),
                            ("UPLOAD_FILE", "Upload File"),
                            ("CREATE_CASE", "Create Case"),
                            ("UPDATE_CASE", "Update Case"),
                            ("DELETE_EVIDENCE", "Delete Evidence"),
                            ("ADD_USER", "Add User to Case"),
                            ("REMOVE_USER", "Remove User from Case"),
                            ("INGEST_DATA", "Ingest UFDR Data"),
                            ("GENERATE_REPORT", "Generate Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("case_id", models.CharField(blank=True, max_length=100)),
                ("evidence_id", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
