# Generated by Django 5.2.6 on 2025-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("pattern", "Pattern Detection"),
                            ("anomaly", "Anomaly Detection"),
                            ("connection", "Connection Discovery"),
                            ("timeline", "Timeline Analysis"),
                            ("entity", "Entity Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("results_count", models.IntegerField(default=0)),
                ("confidence_score", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
