# Generated by Django 5.2.6 on 2025-10-03 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_analysis", "0002_initial"),
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ai_response", "AI Response"),
                            ("evidence", "Evidence Item"),
                            ("insight", "AI Insight"),
                            ("note", "Investigator Note"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("evidence_ids", models.JSONField(blank=True, default=list)),
                ("section", models.CharField(default="findings", max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_items",
                        to="cases.case",
                    ),
                ),
                (
                    "source_query",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_analysis.query",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Report Items",
                "ordering": ["section", "order", "-pinned_at"],
            },
        ),
    ]
