# Generated by Django 5.2.6 on 2025-10-04 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_analysis", "0004_add_chat_sessions"),
        ("cases", "0002_case_cases_case_updated_c10726_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["case", "-created_at"], name="ai_analysis_case_id_d5081b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinsight",
            index=models.Index(
                fields=["insight_type"], name="ai_analysis_insight_50c359_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["case", "-last_message_at"],
                name="ai_analysis_case_id_ef5f8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-last_message_at"],
                name="ai_analysis_user_id_e401d5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["case", "is_active", "-last_message_at"],
                name="ai_analysis_case_id_95a1b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["-created_at"], name="ai_analysis_created_558367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["case", "-created_at"], name="ai_analysis_case_id_64cb21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_analysis_user_id_80d514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportitem",
            index=models.Index(
                fields=["case", "section", "order"],
                name="ai_analysis_case_id_438ab2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportitem",
            index=models.Index(
                fields=["case", "-pinned_at"], name="ai_analysis_case_id_8f6d04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportitem",
            index=models.Index(
                fields=["user", "-pinned_at"], name="ai_analysis_user_id_e92228_idx"
            ),
        ),
    ]
